### ISSUE TITLE
Break the dependency between a ride and a route

### ISSUE THREAD

**Issue by melonpii** [VSangarya/PackTravel#11]
Current:
A ride is a destination.
A route is a child of a ride and it is a way to get to a destination (cab/bus).

Proposal: Our app can live with just rides. The route hierarchy can be removed as it serves no purpose.

**Comment by atharv67** [comment]
What is the final document going to look like in mongo?

**Comment by melonpii** [comment]
> What is the final document going to look like in mongo?
I will come up with a template by tonight and post it here.
