### ISSUE TITLE
Email ride owner when a ride is full

### ISSUE THREAD

**Issue by melonpii** [VSangarya/PackTravel#13]
When ride reaches max occupancy, email ride owner that a ride is full.

**Comment by VSangarya** [comment]
Would this be for a ride and/or a route ?
Since a route can be created by anyone with a limit on the number of passengers as well

**Comment by melonpii** [comment]
It is for the ride. In the last call we had, we decided to break rides and routes because the hierarchy seemed unnecessary. After #16, we only have rides. This PR addresses ride capacity by introducing a new field.

**Comment by atharv67** [comment]
Is anyone working on this?

**Comment by melonpii** [comment]
@qureshi-ali is looking into it.

**Comment by melonpii** [comment]
done in #27
